### ISSUE TITLE
Georeferencing Error: Records found outside named county > .5 mile

### ISSUE THREAD

**Issue by dbloom** [mvz-vertnet/mvz-bird#27]
Hello MVZ,

The Kentucky Department of Fish & Wildlife Resources, Fish and Wildlife Information System (KFWIS) have identified 2 records in the VertNet data portal that should plot within the bounds of the named county in the state of Kentucky, but actually plot outside the named county by half a mile or more.

If you'd like to discuss these issues with the folks at KFWIS, contact me and I will connect you with them.

Records below are Tab-Separated so you should be able to cut/paste into a spreadsheet so you can read them more easily.

institutioncode	collectioncode	catalognumber	county	decimallatitude	decimallongitude	geodeticdatum	coordinateuncertaintyinmeters
MVZ	Bird specimens	79454	Butler County	37.6788	-84.4369	North American Datum 1927	2684
MVZ	Bird specimens	79464	Butler County	37.6788	-84.4369	North American Datum 1927	2684

 (There may not be data contained within each Darwin Core field for each of these records.)

**Comment by mkoo** [comment]
Adding to task queue.
thanks, DB!

**Comment by ccicero** [comment]
fixed by Kelsey Lyberger 5/7/2014.
